version: '3'

services:
  app:
    container_name: minecraft-talk
    image: garzj/minecraft-talk
    build: .
    ports:
      - 8080:8080
      - 3478:3478
    volumes:
      - ./data:/app/server/data
    environment:
      CONVERSATION_SECRET: ${CONVERSATION_SECRET}
      TOKEN_SECRET: ${TOKEN_SECRET}
      ORIGIN: ${ORIGIN}
