name: MinecraftTalk
version: ${project.version}
main: dev.garz.minecrafttalk.MinecraftTalk
api-version: 1.16
api: []
authors: [garzj]
description: A minecraft plugin allowing players to talk inside the game.
commands:
  vc:
    aliases: [voicechat]
    description: Lets you join the voice chat.
    usage: §c/vc { [login|logout] [<player>] } | { modify (set|clear) maxdistance <to> <from> <value> }
